'use client';

import type { FormEvent, ReactNode } from 'react';
import { useEffect, useMemo, useState } from 'react';

type Screen = 'home' | 'free-input' | 'understood' | 'question' | 'current' | 'quest' | 'admin' | 'admin-detail';
type Answers = { deathDate:string; municipality:string; relationship:string; will:string; realEstate:string; assets:string; debt:string; heirs:string; income:string; concern:string };
type AdminStatus = '新規' | '要確認' | '連絡済み' | '相談予約済み' | '対応済み';
type Consultation = Answers & { id:number; name:string; inputAt:string; contact:string; status:AdminStatus; note:string };
type FactStatus = 'confirmed' | 'checking' | 'unconfirmed';
type JourneyFact = { id:string; text:string; status:FactStatus; source:'入力文'|'追加情報'|'質問' };
type QuestId = 'debt' | 'will' | 'documents';
type JourneyState = { started:boolean; freeText:string; facts:JourneyFact[]; answers:Partial<Answers>; questionIndex:number; questStates:Record<QuestId,'todo'|'later'|'done'>; checklist:Record<string,boolean>; questResults:Partial<Record<QuestId,string>>; addedFacts:Array<{id:number;text:string;kind:'new'|'pending'}>; programs:{familyRegistry:'new'|'saved'|'done'} };

const storageKey = 'oyasumi-journey-demo-v1';
const initialJourney: JourneyState = { started:false, freeText:'', facts:[], answers:{}, questionIndex:0, questStates:{debt:'todo',will:'todo',documents:'todo'}, checklist:{}, questResults:{}, addedFacts:[], programs:{familyRegistry:'new'} };
const statusOptions: AdminStatus[] = ['新規','要確認','連絡済み','相談予約済み','対応済み'];
const questionDefinitions = [
  { id:'deathDate' as const, title:'亡くなった日はいつですか？', type:'date' as const },
  { id:'relationship' as const, title:'亡くなった方との関係は？', options:['父・母','配偶者','兄弟姉妹','その他'] },
  { id:'will' as const, title:'遺言書は見つかっていますか？', options:['ある','ない','まだ確認していない','分からない'] },
  { id:'debt' as const, title:'借金やローンについて、今わかっていることはありますか？', options:['ある','ないと思う','まだ調べていない','分からない'] },
  { id:'realEstate' as const, title:'不動産について、現時点でわかっていることはありますか？', options:['ある','ないと思う','まだ調べていない','分からない'] },
  { id:'municipality' as const, title:'亡くなった方の最後の住所の市区町村は分かりますか？', type:'text' as const },
];
const questDefinitions: Array<{id:QuestId;title:string;reason:string;description:string;checklist:string[];results:string[]}> = [
  { id:'debt', title:'借金・ローンの有無を一次確認する', reason:'期間のある制度を確認する際に、手がかりになる情報です。', description:'請求書、通帳、メール、カード、保証に関する書類など、分かる範囲から手がかりを集めます。', checklist:['郵便物・メール・通帳から借入の手がかりを探す','カード・ローン・保証に関する書類を分けて保管する','分からない点を「確認すること」リストに残す'], results:['手がかりが見つかった','今のところ見つからない','まだ確認できていない'] },
  { id:'will', title:'遺言書の保管場所を確認する', reason:'遺言書の有無を確認すると、次に確認する先を整理しやすくなります。', description:'自宅、貸金庫、法務局の自筆証書遺言書保管制度、公証役場などを、分かる範囲で確認します。', checklist:['自宅・貸金庫・大切な書類の保管場所を確認する','法務局の自筆証書遺言書保管制度を確認する','公正証書遺言の有無を公証役場へ確認する方法を調べる'], results:['見つかった','見つからない','まだ確認できていない'] },
  { id:'documents', title:'書類を一か所に集める', reason:'後で窓口に確認するときの材料をそろえるための整理です。', description:'戸籍、住所、財産、債務などを、手続きに応じて必要範囲が変わる資料として分けて保管します。', checklist:['戸籍・住所に関する書類を見つけた範囲で分ける','通帳・証券・不動産・保険の書類を撮影またはコピーする','原本とコピーの保管場所をメモする'], results:['一か所に集めた','一部だけ集めた','まだ集めていない'] },
];

const demoConsultations: Consultation[] = [
  { id:1, name:'田中 花子', inputAt:'2026/08/24 10:32', contact:'hanako.tanaka@example.test', deathDate:'2026-08-18', municipality:'世田谷区', relationship:'父・母', will:'わからない', realEstate:'ある', assets:'ある', debt:'わからない', heirs:'いる', income:'年金と給与があった', concern:'何から手をつければよいか分からない', status:'要確認', note:'' },
  { id:2, name:'佐藤 恒一', inputAt:'2026/08/24 09:10', contact:'koichi.sato@example.test', deathDate:'2026-08-20', municipality:'横浜市', relationship:'配偶者', will:'ない', realEstate:'ある', assets:'ある', debt:'ない', heirs:'いる', income:'年金のみ', concern:'不動産の名義変更について知りたい', status:'新規', note:'' },
  { id:3, name:'鈴木 美咲', inputAt:'2026/08/23 16:45', contact:'misaki.suzuki@example.test', deathDate:'2026-08-12', municipality:'大阪市', relationship:'兄弟姉妹', will:'ある', realEstate:'ない', assets:'わからない', debt:'ない', heirs:'わからない', income:'わからない', concern:'遺言書をどこで確認できるか知りたい', status:'連絡済み', note:'戸籍の取得先を案内する。' },
  { id:4, name:'高橋 恒一', inputAt:'2026/08/22 14:08', contact:'koichi.takahashi@example.test', deathDate:'2026-08-05', municipality:'川崎市', relationship:'父・母', will:'わからない', realEstate:'わからない', assets:'ある', debt:'ある', heirs:'いる', income:'給与のみ', concern:'借入先への確認方法を整理したい', status:'相談予約済み', note:'面談で借入資料を確認する。' },
  { id:5, name:'伊藤 由美', inputAt:'2026/08/21 11:26', contact:'yumi.ito@example.test', deathDate:'2026-07-30', municipality:'さいたま市', relationship:'配偶者', will:'ない', realEstate:'ない', assets:'ある', debt:'ない', heirs:'いない', income:'年金のみ', concern:'必要な書類を整理したい', status:'対応済み', note:'初回案内を送付済み。' },
  { id:6, name:'中村 健', inputAt:'2026/08/20 18:02', contact:'ken.nakamura@example.test', deathDate:'2026-07-28', municipality:'名古屋市', relationship:'その他', will:'わからない', realEstate:'ある', assets:'わからない', debt:'わからない', heirs:'いる', income:'事業・不動産収入があった', concern:'事業と不動産の資料を何から集めるか知りたい', status:'要確認', note:'' },
  { id:7, name:'小林 直子', inputAt:'2026/08/19 13:40', contact:'naoko.kobayashi@example.test', deathDate:'2026-07-25', municipality:'福岡市', relationship:'父・母', will:'ある', realEstate:'ない', assets:'ある', debt:'ない', heirs:'いる', income:'年金のみ', concern:'遺言書の内容を確認する流れを知りたい', status:'新規', note:'' },
];

function statusClass(status:AdminStatus){return `status-${status.replace('相談予約済み','reserved').replace('対応済み','done').replace('連絡済み','contacted').replace('要確認','review').replace('新規','new')}`}
function statusLabel(value:string){return value||'未選択'}
function dateLabel(value:string){ const d=new Date(`${value}T00:00:00`); return Number.isNaN(d.getTime())?'日付未入力':new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric'}).format(d); }
function consultationSummary(item:Consultation){return `相談者の入力では、亡くなった方との関係は「${item.relationship}」、死亡日は${dateLabel(item.deathDate)}です。遺言書は「${item.will}」、不動産は「${item.realEstate}」、預貯金・証券は「${item.assets}」、借金・ローンは「${item.debt}」と回答されています。現在困っていることは「${item.concern}」です。`}
function reviewItems(item:Consultation){return [['借金・ローン',item.debt],['遺言書',item.will],['不動産',item.realEstate],['預貯金・証券',item.assets],['他の相続人候補',item.heirs]].filter(([,value])=>value==='わからない'||value==='') as Array<[string,string]>}

function extractFacts(text:string):JourneyFact[]{
  const facts:JourneyFact[]=[]; const add=(id:string, fact:string, status:FactStatus)=>facts.push({id,text:fact,status,source:'入力文'});
  if(/父|母|お父|お母/.test(text)&&/亡くな|他界|死去/.test(text)) add('relationship','入力文に「父・母」と亡くなったことの記述がありました','confirmed');
  if(/不動産|実家|家|土地|マンション/.test(text)) add('realEstate','不動産がある可能性についての記述がありました','checking');
  if(/銀行|口座|預金|証券|通帳/.test(text)) add('assets','預貯金・証券に関する記述がありました','confirmed');
  if(/借金|ローン|保証|債務/.test(text)) add('debt','借金・ローン・保証債務に関する記述がありました','checking');
  if(/遺言/.test(text)) add('will','遺言書に関する記述がありました','checking');
  if(/兄弟|きょうだい|相続人|子ども|子供/.test(text)) add('heirs','相続人候補に関する記述がありました','checking');
  if(!facts.length) add('none','入力文から事実を自動確定できる項目はまだありません','unconfirmed');
  return facts;
}
function factStatusLabel(status:FactStatus){return status==='confirmed'?'確認できたこと':status==='checking'?'確認中':'まだ分からないこと'}
function factStatusClass(status:FactStatus){return `fact-${status}`}

export default function Home(){
  const [screen,setScreen]=useState<Screen>('home'); const [journey,setJourney]=useState<JourneyState>(initialJourney); const [hydrated,setHydrated]=useState(false); const [selectedQuestId,setSelectedQuestId]=useState<QuestId|null>(null); const [journeyNotice,setJourneyNotice]=useState(''); const [todayFact,setTodayFact]=useState('');
  const [consultations,setConsultations]=useState<Consultation[]>(demoConsultations); const [adminFilter,setAdminFilter]=useState<'すべて'|AdminStatus>('すべて'); const [adminAssetFilter,setAdminAssetFilter]=useState<'すべて'|'借金あり／不明'|'不動産あり'>('すべて'); const [adminSearch,setAdminSearch]=useState(''); const [selectedConsultationId,setSelectedConsultationId]=useState<number|null>(null);
  // Hydration is kept explicit so a saved local journey can reopen without touching the server.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{try{const raw=window.localStorage.getItem(storageKey);if(raw){const saved=JSON.parse(raw) as JourneyState;setJourney({...initialJourney,...saved,questStates:{...initialJourney.questStates,...saved.questStates},programs:{...initialJourney.programs,...saved.programs}})}}catch{/* localStorage is optional */}setHydrated(true)},[]);
  useEffect(()=>{if(hydrated)window.localStorage.setItem(storageKey,JSON.stringify(journey))},[journey,hydrated]);
  const go=(next:Screen)=>{setScreen(next);setJourneyNotice('');window.scrollTo({top:0,behavior:'smooth'})}; const openAdmin=()=>{setSelectedConsultationId(null);go('admin')}; const openConsultation=(id:number)=>{setSelectedConsultationId(id);go('admin-detail')}; const updateConsultation=(id:number,changes:Partial<Consultation>)=>setConsultations(items=>items.map(item=>item.id===id?{...item,...changes}:item)); const updateJourney=(changes:Partial<JourneyState>)=>setJourney(prev=>({...prev,...changes}));
  const startFreeInput=(e:FormEvent)=>{e.preventDefault();if(!journey.freeText.trim()){setJourneyNotice('まずは書ける範囲で、状況を入力してください。');return}updateJourney({started:true,facts:extractFacts(journey.freeText)});go('understood')}; const startQuestions=()=>{updateJourney({started:true,questionIndex:0});go('question')};
  const answerQuestion=(id:keyof Answers,value:string)=>{const nextAnswers={...journey.answers,[id]:value};const definition=questionDefinitions[journey.questionIndex];const newFact:JourneyFact={id:`question-${id}`,text:`${definition.title}：「${value}」`,status:'confirmed',source:'質問'};const facts=[...journey.facts.filter(f=>f.id!==newFact.id),newFact];if(journey.questionIndex+1<questionDefinitions.length)updateJourney({answers:nextAnswers,facts,questionIndex:journey.questionIndex+1});else{updateJourney({answers:nextAnswers,facts,questionIndex:0,started:true});go('current')}};
  const confirmFact=(id:string,status:FactStatus)=>updateJourney({facts:journey.facts.map(f=>f.id===id?{...f,status}:f)}); const progress=useMemo(()=>{const answersCount=Object.values(journey.answers).filter(Boolean).length;const doneCount=Object.values(journey.questStates).filter(v=>v==='done').length;return Math.min(92,journey.started?Math.max(25,25+answersCount*5+doneCount*12+(journey.addedFacts.length?5:0)):0)},[journey]); const confirmedFacts=journey.facts.filter(f=>f.status==='confirmed'); const checkingFacts=journey.facts.filter(f=>f.status==='checking'); const unknownFacts=journey.facts.filter(f=>f.status==='unconfirmed'); const nextQuest=questDefinitions.find(q=>journey.questStates[q.id]==='todo')??questDefinitions.find(q=>journey.questStates[q.id]==='later'); const selectedQuest=questDefinitions.find(q=>q.id===selectedQuestId)??null;
  const openQuest=(id:QuestId)=>{setSelectedQuestId(id);go('quest')}; const toggleChecklist=(key:string)=>updateJourney({checklist:{...journey.checklist,[key]:!journey.checklist[key]}}); const setQuestResult=(id:QuestId,value:string)=>updateJourney({questResults:{...journey.questResults,[id]:value}}); const completeQuest=()=>{if(!selectedQuestId)return;updateJourney({questStates:{...journey.questStates,[selectedQuestId]:'done'}});setJourneyNotice('確認内容を更新しました。現在地に反映しています。');go('current')}; const laterQuest=()=>{if(!selectedQuestId)return;updateJourney({questStates:{...journey.questStates,[selectedQuestId]:'later'}});setJourneyNotice('この確認は後で見返せるように残しました。');go('current')}; const addTodayFact=(e:FormEvent)=>{e.preventDefault();const text=todayFact.trim();if(!text)return;const kind=/分からない|まだ|不明|確認中|未確認/.test(text)?'pending':'new';updateJourney({addedFacts:[...journey.addedFacts,{id:Date.now(),text,kind}]});setTodayFact('');setJourneyNotice(kind==='pending'?'「確認が必要なこと」として追加しました。':'新しく分かったこととして追加しました。')}; const resetJourney=()=>{window.localStorage.removeItem(storageKey);setJourney(initialJourney);setTodayFact('');setJourneyNotice('');go('home')}; const saveProgram=(value:'saved'|'done')=>updateJourney({programs:{familyRegistry:value}});
  const visibleConsultations=useMemo(()=>consultations.filter(item=>{const matchesFilter=adminFilter==='すべて'||item.status===adminFilter;const matchesAsset=adminAssetFilter==='すべて'||(adminAssetFilter==='不動産あり'&&item.realEstate==='ある')||(adminAssetFilter==='借金あり／不明'&&(item.debt==='ある'||item.debt==='わからない'));const q=adminSearch.trim().toLowerCase();const matchesSearch=!q||`${item.name} ${item.municipality}`.toLowerCase().includes(q);return matchesFilter&&matchesAsset&&matchesSearch}),[consultations,adminFilter,adminAssetFilter,adminSearch]); const selectedConsultation=consultations.find(item=>item.id===selectedConsultationId)??null; const adminCounts=useMemo(()=>({new:consultations.filter(item=>item.status==='新規').length,review:consultations.filter(item=>item.status==='要確認').length,reserved:consultations.filter(item=>item.status==='相談予約済み').length,done:consultations.filter(item=>item.status==='対応済み').length}),[consultations]);

  return <div className="app-shell">
    <header className="site-header"><button className="brand" onClick={()=>go('home')}><span className="brand-mark">結</span><span><b>おやすみ手続きナビ</b><small>相続の初期整理を、ひとつずつ。</small></span></button><div className="header-actions">{screen==='admin'||screen==='admin-detail'?<button className="admin-demo-link" onClick={()=>go('home')}>一般画面へ戻る</button>:<button className="admin-demo-link" onClick={openAdmin}>事業者向けデモ</button>}<span className="header-note">無料・登録不要</span></div></header>

    {screen==='admin'&&<main className="admin-screen"><div className="admin-heading"><div><p className="eyebrow">事業者向け管理画面</p><h1>おやすみ手続きナビ｜事業者向け</h1><p>デモ管理画面 · 相談前に状況を整理することで、初回ヒアリングの時間を短縮し、確認漏れを減らします。</p></div><span className="admin-demo-badge">DEMO</span></div><div className="admin-summary-grid"><article><span>新規相談</span><b>{adminCounts.new}</b><small>入力直後の相談</small></article><article className="is-review"><span>要確認</span><b>{adminCounts.review}</b><small>追加確認が必要な項目あり</small></article><article><span>相談予約済み</span><b>{adminCounts.reserved}</b><small>次回相談につながった相談</small></article><article><span>対応済み</span><b>{adminCounts.done}</b><small>対応メモを残した相談</small></article></div><section className="admin-panel"><div className="admin-panel-heading"><div><p className="eyebrow">相談者一覧</p><h2>事前ヒアリング</h2></div><span>{visibleConsultations.length}件表示</span></div><div className="admin-toolbar"><label className="admin-search"><span>検索</span><input type="search" placeholder="相談者名・市区町村で検索" value={adminSearch} onChange={e=>setAdminSearch(e.target.value)}/></label><label><span>ステータス</span><select value={adminFilter} onChange={e=>setAdminFilter(e.target.value as 'すべて'|AdminStatus)}><option>すべて</option>{statusOptions.map(status=><option key={status}>{status}</option>)}</select></label><label><span>確認条件</span><select value={adminAssetFilter} onChange={e=>setAdminAssetFilter(e.target.value as 'すべて'|'借金あり／不明'|'不動産あり')}><option>すべて</option><option>借金あり／不明</option><option>不動産あり</option></select></label></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>相談者</th><th>入力日時</th><th>関係</th><th>死亡日</th><th>不動産</th><th>借金</th><th>遺言</th><th>ステータス</th><th></th></tr></thead><tbody>{visibleConsultations.map(item=><tr key={item.id}><td><b>{item.name}</b><small>{item.municipality}</small></td><td>{item.inputAt}</td><td>{item.relationship}</td><td>{dateLabel(item.deathDate)}</td><td><span className={`value-chip ${item.realEstate==='ある'?'is-yes':''}`}>{statusLabel(item.realEstate)}</span></td><td><span className={`value-chip ${item.debt==='わからない'?'is-unknown':item.debt==='ある'?'is-yes':''}`}>{statusLabel(item.debt)}</span></td><td><span className={`value-chip ${item.will==='わからない'?'is-unknown':''}`}>{statusLabel(item.will)}</span></td><td><select className={`status-select ${statusClass(item.status)}`} value={item.status} onChange={e=>updateConsultation(item.id,{status:e.target.value as AdminStatus})}>{statusOptions.map(status=><option key={status}>{status}</option>)}</select></td><td><button className="detail-button" onClick={()=>openConsultation(item.id)}>詳細を見る →</button></td></tr>)}</tbody></table>{visibleConsultations.length===0&&<p className="empty-state">条件に一致する相談者はいません。</p>}</div></section></main>}

    {screen==='admin-detail'&&selectedConsultation&&<main className="admin-screen"><div className="admin-detail-top"><button className="back-admin" onClick={()=>go('admin')}>← 相談者一覧へ戻る</button><span className="admin-demo-badge">デモ管理画面</span></div><section className="detail-heading"><div><p className="eyebrow">相談者詳細</p><h1>{selectedConsultation.name}</h1><p>入力日時：{selectedConsultation.inputAt}</p></div><label className={`detail-status ${statusClass(selectedConsultation.status)}`}><span>対応ステータス</span><select value={selectedConsultation.status} onChange={e=>updateConsultation(selectedConsultation.id,{status:e.target.value as AdminStatus})}>{statusOptions.map(status=><option key={status}>{status}</option>)}</select></label></section><section className="admin-detail-grid"><article className="admin-detail-card"><h2>基本情報</h2><dl><div><dt>入力日時</dt><dd>{selectedConsultation.inputAt}</dd></div><div><dt>相談者名</dt><dd>{selectedConsultation.name}</dd></div><div><dt>連絡先</dt><dd>{selectedConsultation.contact}</dd></div><div><dt>亡くなった方との関係</dt><dd>{selectedConsultation.relationship}</dd></div><div><dt>死亡日</dt><dd>{dateLabel(selectedConsultation.deathDate)}</dd></div><div><dt>最後の住所</dt><dd>{selectedConsultation.municipality}</dd></div></dl></article><article className="admin-detail-card"><h2>相続状況</h2><dl><div><dt>遺言書</dt><dd>{selectedConsultation.will}</dd></div><div><dt>不動産</dt><dd>{selectedConsultation.realEstate}</dd></div><div><dt>預貯金・証券</dt><dd>{selectedConsultation.assets}</dd></div><div><dt>借金・ローン</dt><dd>{selectedConsultation.debt}</dd></div><div><dt>他の相続人候補</dt><dd>{selectedConsultation.heirs}</dd></div><div><dt>亡くなった年の収入</dt><dd>{selectedConsultation.income}</dd></div></dl></article></section><section className="admin-detail-card concern-card"><h2>現在困っていること</h2><p>{selectedConsultation.concern}</p><small>相談者の自由入力をそのまま表示しています。法的な自動分析には使いません。</small></section><section className="admin-detail-card"><div className="section-heading-row"><div><h2>事前ヒアリング要約</h2><small>入力情報の要約</small></div></div><p className="summary-copy">{consultationSummary(selectedConsultation)}</p></section><section className="admin-detail-card"><h2>確認ポイント</h2><p className="admin-card-note">入力データ上、追加確認した方がよい未確認項目です。法的な評価や結論ではありません。</p>{reviewItems(selectedConsultation).length?<ul className="review-list">{reviewItems(selectedConsultation).map(([label,value])=><li key={label}><span>{label}</span><b>{value||'未入力'}</b></li>)}</ul>:<p className="no-review">未確認として登録されている項目はありません。</p>}</section><section className="admin-detail-card note-card"><div className="section-heading-row"><div><h2>次回相談用メモ</h2><small>電話・面談・資料依頼など</small></div><span>この端末上のデモ状態のみ</span></div><textarea rows={5} placeholder="電話で確認すること、面談で聞くこと、持参を依頼する資料など" value={selectedConsultation.note} onChange={e=>updateConsultation(selectedConsultation.id,{note:e.target.value})}/><p>このメモはブラウザ内のReact stateで扱うデモ用です。サーバーへ保存・送信されません。</p></section></main>}

    {screen==='home'&&<main className="journey-shell"><section className="journey-hero"><div><p className="eyebrow">大切な方を亡くされた直後のために</p><h1>相続、<br/><em>何から手をつければいい？</em></h1><p className="journey-lead">今わかっていることから整理して、次に確認することをひとつずつ見つけます。</p><p className="journey-reassure">全部を一度に理解する必要はありません。</p>{journey.started?<div className="resume-card"><span>前回の続きから</span><b>情報整理：{progress}%</b><small>{nextQuest?`次は「${nextQuest.title}」を確認します。`:'確認内容を見返せます。'}</small><button className="primary" onClick={()=>go('current')}>続きから見る <span>→</span></button><button className="text-button" onClick={resetJourney}>最初からやり直す</button></div>:<><button className="primary" onClick={()=>go('free-input')}>整理をはじめる <span>→</span></button><p className="privacy">✓ 入力内容はこの端末のブラウザにのみ保存できます　　登録不要</p></>}</div><div className="journey-map"><p>進め方</p><div><span>1</span><b>書ける範囲で伝える</b><small>自由入力か質問から選べます</small></div><i/><div><span>2</span><b>ここまで分かったことを確認</b><small>推測はせず、修正できます</small></div><i/><div><span>3</span><b>次の確認をひとつ選ぶ</b><small>あとでやることもできます</small></div></div></section><section className="journey-trust"><div><b>法律判断はしません</b><p>一般的な確認事項を整理するデモです。</p></div><div><b>分からないままで大丈夫</b><p>確認中の項目として残せます。</p></div><div><b>端末内だけに保存</b><p>サーバーやDBへ送信しません。</p></div></section></main>}

    {screen==='free-input'&&<main className="journey-page"><JourneyProgress label="最初の入力" step="1 / 3"/><section className="journey-panel intro-panel"><p className="eyebrow">書ける範囲で大丈夫です</p><h1>いまの状況を、言葉にしてみる</h1><p>まとまっていなくても大丈夫です。入力した文章は、事実を自動で確定するためではなく、確認のきっかけを見つけるために使います。</p><form onSubmit={startFreeInput}><textarea className="journey-input" rows={8} placeholder="例：父が亡くなりました。実家と銀行口座がありそうですが、借金があるかは分かりません。何から始めればいいか知りたいです。" value={journey.freeText} onChange={e=>updateJourney({freeText:e.target.value})}/><small>書ける範囲で大丈夫です。固有名詞や個人情報は入力しないでください。</small>{journeyNotice&&<p className="journey-error" role="alert">{journeyNotice}</p>}<div className="actions"><button type="button" className="text-button" onClick={()=>go('home')}>← 戻る</button><button className="primary">ここまで整理する <span>→</span></button></div></form></section><section className="alternate-card"><b>文章より質問の方が答えやすい方へ</b><p>死亡日や市区町村などを、ひとつずつ確認できます。</p><button className="outline" onClick={startQuestions}>質問に答えて整理する</button></section></main>}

    {screen==='understood'&&<main className="journey-page"><JourneyProgress label="ここまで分かりました" step="2 / 3"/><section className="journey-panel"><p className="eyebrow">入力文から見つかった手がかり</p><h1>ここまで分かりました</h1><p>文章から読み取れたキーワードを、確定せずに表示しています。合っていないものは「要修正」にしてください。</p><blockquote className="input-quote">{journey.freeText}</blockquote><div className="fact-list">{journey.facts.map(fact=><article key={fact.id} className={`fact-card ${factStatusClass(fact.status)}`}><div><span className="fact-badge">{factStatusLabel(fact.status)}</span><p>{fact.text}</p></div>{fact.id!=='none'&&<div className="fact-actions"><button onClick={()=>confirmFact(fact.id,'confirmed')}>この理解で合っています</button><button onClick={()=>confirmFact(fact.id,'checking')}>要修正・確認中</button></div>}</article>)}</div><p className="quiet-note">自動推測で法律上の結論を出すことはありません。追加の質問で、分かる範囲を補えます。</p><div className="actions"><button className="text-button" onClick={()=>go('free-input')}>← 入力を修正</button><div><button className="outline" onClick={()=>go('current')}>いったん現在地を見る</button><button className="primary inline-primary" onClick={startQuestions}>不足情報を確認する <span>→</span></button></div></div></section></main>}

    {screen==='question'&&<main className="journey-page"><JourneyProgress label="不足情報をひとつずつ確認" step={`${journey.questionIndex+1} / ${questionDefinitions.length}`}/>{(()=>{const q=questionDefinitions[journey.questionIndex];const inputType=q.type==='date'?'date':'text';return <section className="journey-panel single-question"><p className="eyebrow">確認 {journey.questionIndex+1} / {questionDefinitions.length}</p><h1>{q.title}</h1><p>答えに迷ったら「まだ確認していない」「分からない」を選べます。</p>{q.type?<form onSubmit={e=>{e.preventDefault();const value=(e.currentTarget.elements.namedItem(q.id) as HTMLInputElement).value.trim();if(value)answerQuestion(q.id,value)}}><input name={q.id} type={inputType} className="journey-text-input" placeholder={q.id==='municipality'?'例：世田谷区、横浜市':undefined} defaultValue={journey.answers[q.id]||''}/><button className="primary">次へ <span>→</span></button></form>:<div className="answer-options">{q.options?.map(option=><button key={option} onClick={()=>answerQuestion(q.id,option)}>{option}<span>→</span></button>)}</div>}<button className="text-button question-later" onClick={()=>go('current')}>いったん現在地を見る</button></section>})()}</main>}

    {screen==='current'&&<main className="journey-page current-page"><section className="current-hero"><div><p className="eyebrow">いまの整理状況</p><h1>あなたの現在地</h1><p>ここで表示するのは、入力・確認項目の整理状況です。法的な手続きの完了度ではありません。</p></div><div className="progress-orb"><strong>{progress}%</strong><small>情報整理</small></div></section><section className="progress-panel"><div className="progress-label"><b>情報整理：{progress}%</b><span>分かっていることを少しずつ</span></div><div className="progress-bar"><i style={{width:`${progress}%`}}/></div></section><section className="status-groups"><FactGroup title="確認できたこと" tone="confirmed" facts={confirmedFacts}/><FactGroup title="確認中" tone="checking" facts={checkingFacts}/><FactGroup title="まだ分からないこと" tone="unconfirmed" facts={unknownFacts}/></section>{journey.addedFacts.length>0&&<section className="added-facts"><h2>今日追加したメモ</h2>{journey.addedFacts.map(f=><p key={f.id}><span>{f.kind==='new'?'新しく分かったこと':'確認が必要なこと'}</span>{f.text}</p>)}</section>}{journeyNotice&&<p className="journey-notice" role="status">{journeyNotice}</p>}<section className="next-quest"><div className="section-kicker">次に確認すること</div>{nextQuest?<><h2>{nextQuest.title}</h2><p>{nextQuest.reason}</p><div className="quest-state-row"><span className={`quest-state state-${journey.questStates[nextQuest.id]}`}>{journey.questStates[nextQuest.id]==='later'?'後で確認':'おすすめ'}</span><button className="primary" onClick={()=>openQuest(nextQuest.id)}>確認をはじめる <span>→</span></button></div></>:<p>今表示されている確認項目を、必要なときに見返してください。</p>}</section><section className="today-panel"><div><p className="section-kicker">小さな更新</p><h2>今日、何か分かったことはありますか？</h2><p>新しく分かったことと、まだ確認が必要なことを区別して残します。</p></div><form onSubmit={addTodayFact}><textarea rows={3} placeholder="例：通帳が2冊見つかった／借金はまだ分からない" value={todayFact} onChange={e=>setTodayFact(e.target.value)}/><button className="outline">整理状況に追加</button></form></section><ProgramCard status={journey.programs.familyRegistry} onSave={saveProgram}/><Timeline/><section className="local-note"><b>この端末のブラウザにのみ保存されます</b><p>ログイン・サーバー保存・外部送信はありません。共有端末では使い終わったら初期化してください。</p><button className="reset-button" onClick={resetJourney}>このデモの入力・進捗を初期化</button></section></main>}

    {screen==='quest'&&selectedQuest&&<main className="journey-page"><JourneyProgress label="次の確認" step="3 / 3"/><section className="quest-detail"><p className="eyebrow">確認クエスト</p><h1>{selectedQuest.title}</h1><p className="quest-description">{selectedQuest.description}</p><div className="quest-checklist"><h2>確認リスト</h2>{selectedQuest.checklist.map((item,index)=>{const key=`${selectedQuest.id}:${index}`;return <label key={key}><input type="checkbox" checked={Boolean(journey.checklist[key])} onChange={()=>toggleChecklist(key)}/><span>{item}</span></label>})}</div><label className="quest-result"><span>いまの結果を選ぶ（途中でも大丈夫です）</span><select value={journey.questResults[selectedQuest.id]||''} onChange={e=>setQuestResult(selectedQuest.id,e.target.value)}><option value="">選択してください</option>{selectedQuest.results.map(result=><option key={result}>{result}</option>)}</select></label><p className="quiet-note">この画面は確認した内容を整理するためのものです。相続放棄などの要否や法律上の結論は表示しません。</p><div className="actions"><button className="text-button" onClick={()=>go('current')}>← 現在地へ戻る</button><div><button className="outline" onClick={laterQuest}>あとでやる</button><button className="primary inline-primary" onClick={completeQuest}>確認内容を更新する</button></div></div></section></main>}
    <footer><b>おやすみ手続きナビ</b><p>大切なときに、迷わないための道しるべ。</p><small>© 2026 Prototype — 入力内容はこの端末のブラウザにのみ保存されます</small></footer>
  </div>;
}

function JourneyProgress({label,step}:{label:string;step:string}){return <div className="journey-progress"><span>{step}</span><i/><b>{label}</b></div>}
function FactGroup({title,tone,facts}:{title:string;tone:FactStatus;facts:JourneyFact[]}){return <section className={`fact-group ${factStatusClass(tone)}`}><h2>{title}<span>{facts.length}</span></h2>{facts.length?<ul>{facts.map(f=><li key={f.id}>{f.text}</li>)}</ul>:<p>まだ登録されていません。</p>}</section>}
function ProgramCard({status,onSave}:{status:'new'|'saved'|'done';onSave:(value:'saved'|'done')=>void}){return <section className="program-card"><div><p className="section-kicker">知っておきたい制度</p><h2>法定相続情報証明制度</h2><p>相続関係を一覧にした図を法務局が認証する制度です。利用できるかどうかや必要書類は、公式案内で確認してください。</p></div><div className="program-actions"><OfficialLink href="https://houmukyoku.moj.go.jp/homu/static/index.html">公式情報を見る</OfficialLink><button className={status==='saved'?'is-saved':''} onClick={()=>onSave('saved')}>{status==='saved'?'確認リストに追加済み':'確認リストに追加'}</button><button onClick={()=>onSave('done')}>{status==='done'?'確認済み':'後で見る'}</button></div></section>}
function Timeline(){return <section className="timeline-card"><div className="section-kicker">見通しをつくる</div><h2>手続きタイムライン</h2><p className="timeline-note">一般的な手続きの目安です。起算日・要否は状況や制度によって異なります。</p><div className="journey-timeline"><TimeItem when="いま" title="初期確認・資料集め">遺言書、相続人候補、財産と債務の手がかりを整理します。</TimeItem><TimeItem when="原則3か月以内｜起算日は状況によって異なります" title={<OfficialLink href="https://www.courts.go.jp/saiban/syurui/syurui_kazi/kazi_06_13/index.html">相続放棄・限定承認の検討</OfficialLink>}>期間がある制度です。具体的な期限は家庭裁判所の公式案内で確認してください。</TimeItem><TimeItem when="一般的な目安｜4か月以内となる場合" title={<OfficialLink href="https://www.nta.go.jp/taxes/shiraberu/taxanswer/shotoku/2022.htm">準確定申告</OfficialLink>}>必要となる場合があります。要否や起算日は国税庁・税務署へ確認してください。</TimeItem><TimeItem when="一般的な目安｜10か月以内となる場合" title={<OfficialLink href="https://www.nta.go.jp/taxes/tetsuzuki/shinsei/shinkoku/sozoku/sozoku.htm">相続税の申告・納付</OfficialLink>}>必要となる場合があります。具体的な情報は国税庁の公式案内で確認してください。</TimeItem></div><p className="official-cta"><b>重要な制度は、公式情報を確認してください。</b> <OfficialLink href="https://www.courts.go.jp/">裁判所</OfficialLink>・<OfficialLink href="https://www.nta.go.jp/">国税庁</OfficialLink></p></section>}
function TimeItem({when,title,children}:{when:string;title:ReactNode;children:ReactNode}){return <div className="time-item"><i/><div><time>{when}</time><b>{title}</b><p>{children}</p></div></div>}
function OfficialLink({href,children}:{href:string;children:ReactNode}){return <a className="official-link" href={href} target="_blank" rel="noreferrer" title="国の機関による案内を新しいタブで開く">{children}<span aria-hidden="true">↗</span></a>}
